  mysql:
    image: mysql
    container_name: dev-db
    restart: always

    cap_add:
      - SYS_NICE 

    environment:
      API_PORT: 3001
  
      MYSQL_USER: eliHC
      MYSQL_PASSWORD: 170300
      MYSQL_ROOT_PASSWORD: root
  
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: delivery-app
      EVAL_ALWAYS_RESTORE_DEV_DB: 'true'

    ports:
     - 3333:3306

    volumes:
      - ./:/app
